"use client";
import { WorkspaceHeader } from "@/components/ui/workspace-ui";
import { useState } from "react";
import { Check, CheckCircle2, ChevronDown, Plus, Search, Sparkles, Truck } from "lucide-react";
import { orders, type Product } from "@/lib/data";
import { orderStyles, surfaceStyles } from "@/lib/ui-classes";
function money(value: number) { return new Intl.NumberFormat("da-DK", { style: "currency", currency: "DKK", maximumFractionDigits: 0 }).format(value); }
export function OrdersWorkspace({ products, setProducts, onNewOrder, notify }: { products:Product[]; setProducts:React.Dispatch<React.SetStateAction<Product[]>>; onNewOrder: () => void; notify: (s: string) => void }) {
  const [received,setReceived]=useState<string[]>([]);
  const [query,setQuery]=useState("");
  const [statusFilter,setStatusFilter]=useState("ALL");
  const suggestions=products.filter(p=>p.active!==false&&p.stock<p.par).map(p=>({...p,qty:p.par-p.stock}));
  const visibleOrders=orders.filter(order=>{ const status=received.includes(order.id)?"Delivered":order.status; const matchesQuery=!query.trim()||`${order.id} ${order.supplier}`.toLowerCase().includes(query.trim().toLowerCase()); return matchesQuery&&(statusFilter==="ALL"||status.toUpperCase()===statusFilter); });
  function receive(orderId:string){ if(received.includes(orderId))return; setReceived(cur=>[...cur,orderId]); if(orderId==="PO-1048") setProducts(cur=>cur.map(p=>p.supplier==="Nordic Drinks"?{...p,stock:p.stock+Math.max(0,p.par-p.stock)}:p)); notify(`${orderId} received and stock updated`); }
  return <div className={`${surfaceStyles.workspace} page-flow`}><WorkspaceHeader title="Purchase orders" description="Replenishment, deliveries and order status." actions={<button className={`${surfaceStyles.control} ${surfaceStyles.solid} ${orderStyles.addButton}`} onClick={onNewOrder}><Plus size={18} /> New order</button>} />
    {suggestions.length>0&&<section className={orderStyles.suggestion}><div><Sparkles size={19}/><div><p>Suggested replenishment</p><strong>{suggestions.length} products below par</strong><small>{suggestions.reduce((n,p)=>n+p.qty,0)} units suggested</small></div></div><button className={surfaceStyles.control} onClick={()=>notify("Suggested order grouped by supplier and saved as draft")}>Create draft</button></section>}
    <section className={orderStyles.delivery}><div><Truck size={20}/><div><p>Next delivery</p><strong>Nordic Drinks</strong><small>Tomorrow · 08:00–11:00</small></div></div><button className={surfaceStyles.control} onClick={() => receive("PO-1048")}>{received.includes("PO-1048")?<><Check size={16}/>Received</>:"Receive"}</button></section>
    <section className={orderStyles.ordersPanel}><div className={`${surfaceStyles.toolbar} ${orderStyles.toolbar}`}><div className={surfaceStyles.search}><Search size={17} /><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search orders" aria-label="Search orders" /></div><label className={orderStyles.filter}><span className="sr-only">Filter order status</span><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="ALL">All statuses</option><option value="DRAFT">Draft</option><option value="CONFIRMED">Confirmed</option><option value="DELIVERED">Delivered</option></select><ChevronDown size={15}/></label>{(query||statusFilter!=="ALL")&&<button type="button" className={`${surfaceStyles.control} ${orderStyles.clear}`} onClick={()=>{setQuery("");setStatusFilter("ALL")}}>Clear</button>}<span className={orderStyles.resultCount} role="status" aria-live="polite">{visibleOrders.length} order{visibleOrders.length===1?"":"s"}</span></div><div className={orderStyles.orderList}>{visibleOrders.length?visibleOrders.map((order) => {const currentStatus=received.includes(order.id)?"Received":order.status;return <article className={`${surfaceStyles.card} ${orderStyles.orderCard}`} key={order.id}><header className={surfaceStyles.cardHeader}><div><p>{order.id}</p><h2>{order.supplier}</h2></div><span data-status={currentStatus.toLowerCase()}>{currentStatus}</span></header><dl><div><dt>Items</dt><dd>{order.items}</dd></div><div><dt>Delivery</dt><dd>{order.delivery}</dd></div><div><dt>Amount</dt><dd>{money(order.amount)}</dd></div></dl>{order.status!=="Delivered"&&!received.includes(order.id)&&<button className={`${surfaceStyles.control} ${surfaceStyles.solid} ${orderStyles.receiveButton}`} onClick={()=>receive(order.id)}><CheckCircle2 size={16}/> Receive order</button>}</article>}):<div className={`${surfaceStyles.empty} ${orderStyles.empty}`}><strong>No orders found</strong><span>Change the search or status filter.</span></div>}</div></section>
  </div>
}

