import { requireUser } from '@/lib/auth/session'; import { db } from '@/lib/db/client'; import { ClaimShiftButton,TransferResponse,TransferShiftButton } from './shift-actions';
type ShiftRow={id:string;starts_at:Date;ends_at:Date;role:string;status:string;location_name:string;notes:string|null};
export default async function MyShifts(){const u=await requireUser();if(!u.employeeId)return <div className="employee-page"><h1>Schedule unavailable</h1><p className="employee-lead">Your login is not linked to an employee profile.</p></div>;const [location,rows,open,people,swaps,transfers,claims]=await Promise.all([
 db()<Array<{timezone:string}>>`select timezone from locations where id=${u.locationId} and organization_id=${u.organizationId} limit 1`,
 db()<ShiftRow[]>`select s.id,s.starts_at,s.ends_at,s.role,s.status,l.name location_name,s.notes from shifts s join locations l on l.id=s.location_id where s.organization_id=${u.organizationId} and s.employee_id=${u.employeeId} and s.status in ('PUBLISHED','CONFIRMED') and s.ends_at>now()-interval '1 day' order by s.starts_at limit 40`,
 db()<ShiftRow[]>`select s.id,s.starts_at,s.ends_at,s.role,s.status,l.name location_name,s.notes from shifts s join locations l on l.id=s.location_id where s.organization_id=${u.organizationId} and s.status='PUBLISHED' and s.is_open=true and s.employee_id is null and s.starts_at>now() order by s.starts_at limit 30`,
 db()<Array<{id:string;name:string}>>`select id,first_name||' '||last_name name from employees where organization_id=${u.organizationId} and active=true and id<>${u.employeeId} order by first_name`,
 db()<Array<{id:string;label:string}>>`select s.id,e.first_name||' '||e.last_name||' · '||to_char(s.starts_at,'Dy DD Mon HH24:MI') label from shifts s join employees e on e.id=s.employee_id where s.organization_id=${u.organizationId} and s.status='PUBLISHED' and s.employee_id<>${u.employeeId} and s.starts_at>now() order by s.starts_at limit 50`,
 db()<Array<{id:string;type:string;status:string;starts_at:Date;ends_at:Date;role:string;target_name:string|null;requested_by_name:string}>>`select t.id,t.type,t.status,s.starts_at,s.ends_at,s.role,te.first_name||' '||te.last_name target_name,re.first_name||' '||re.last_name requested_by_name from shift_transfers t join shifts s on s.id=t.shift_id join employees re on re.id=t.requested_by_employee_id left join employees te on te.id=t.target_employee_id where t.organization_id=${u.organizationId} and (t.requested_by_employee_id=${u.employeeId} or t.target_employee_id=${u.employeeId}) order by t.created_at desc limit 20`,
 db()<Array<{shift_id:string;status:string}>>`select shift_id,status from shift_claims where organization_id=${u.organizationId} and employee_id=${u.employeeId} order by created_at desc`
]);const tz=location[0]?.timezone||'Europe/Copenhagen';const claimMap=new Map(claims.map(c=>[c.shift_id,c.status]));const incoming=transfers.filter(t=>t.status==='PENDING_EMPLOYEE'&&t.target_name);return <div className="employee-page"><p className="eyebrow">Schedule</p><h1>My schedule</h1><p className="employee-lead">Published shifts, available shifts and exchange requests.</p>{incoming.length>0&&<><h2>Needs your response</h2><section className="employee-inbox">{incoming.map(t=><article key={t.id}><div><strong>{t.requested_by_name} wants to {t.type==='SWAP'?'swap':'hand over'} a shift</strong><p>{date(t.starts_at,tz)} · {time(t.starts_at,tz)}–{time(t.ends_at,tz)} · {t.role}</p></div><TransferResponse transferId={t.id}/></article>)}</section></>}<h2>Upcoming</h2><section className="shift-feed">{rows.map(r=><article key={r.id}><DateTile date={r.starts_at} tz={tz}/><div><span className="portal-status">PUBLISHED</span><h2>{r.role}</h2><p>{time(r.starts_at,tz)}–{time(r.ends_at,tz)} · {r.location_name}</p>{r.notes&&<small>{r.notes}</small>}<div className="shift-action-row"><TransferShiftButton shiftId={r.id} people={people} swapShifts={swaps}/></div></div></article>)}{!rows.length&&<div className="empty-portal">No published shifts yet.</div>}</section><h2 className="history-title">Available shifts</h2><section className="shift-feed">{open.map(r=>{const claim=claimMap.get(r.id);return <article className="available-shift-card" key={r.id}><DateTile date={r.starts_at} tz={tz}/><div><span className="portal-status">OPEN SHIFT</span><h2>{r.role}</h2><p>{time(r.starts_at,tz)}–{time(r.ends_at,tz)} · {r.location_name}</p>{claim?<span className={`claim-state claim-${claim.toLowerCase()}`}>{claim}</span>:<div className="shift-action-row"><ClaimShiftButton shiftId={r.id}/></div>}</div></article>})}{!open.length&&<div className="empty-portal">No available shifts right now.</div>}</section>{transfers.length>0&&<><h2 className="history-title">Exchange history</h2><section className="request-history">{transfers.map(t=><article key={t.id}><div><strong>{t.type==='SWAP'?'Shift swap':'Shift handover'}</strong><p>{date(t.starts_at,tz)} · {t.target_name||'No target'}</p></div><span className={`request-${t.status.toLowerCase()}`}>{t.status.replaceAll('_',' ')}</span></article>)}</section></>}</div>}
function DateTile({date:dateValue,tz}:{date:Date;tz:string}){const d=new Date(dateValue);return <div className="shift-date"><b>{new Intl.DateTimeFormat('en',{weekday:'short',timeZone:tz}).format(d)}</b><strong>{new Intl.DateTimeFormat('en',{day:'2-digit',timeZone:tz}).format(d)}</strong><span>{new Intl.DateTimeFormat('en',{month:'short',timeZone:tz}).format(d)}</span></div>}
function time(d:Date,tz:string){return new Intl.DateTimeFormat('en-DK',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:tz}).format(new Date(d))} function date(d:Date,tz:string){return new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',timeZone:tz}).format(new Date(d))}
