import Link from 'next/link'; import { Bell,CalendarDays,ChevronRight,Clock3,Umbrella } from 'lucide-react'; import { requireUser } from '@/lib/auth/session'; import { db } from '@/lib/db/client';
export default async function EmployeeHome(){const u=await requireUser();if(!u.employeeId)return <div className="employee-page"><h1>Welcome</h1><p className="employee-lead">Your account needs to be linked to an employee profile.</p></div>;const [location,shifts,active,requests,transfers,notifications]=await Promise.all([
 db()<Array<{timezone:string}>>`select timezone from locations where id=${u.locationId} and organization_id=${u.organizationId} limit 1`,
 db()<Array<{id:string;starts_at:Date;ends_at:Date;role:string;location_name:string}>>`select s.id,s.starts_at,s.ends_at,s.role,l.name location_name from shifts s join locations l on l.id=s.location_id where s.organization_id=${u.organizationId} and s.employee_id=${u.employeeId} and s.status in ('PUBLISHED','CONFIRMED') and s.ends_at>now() order by s.starts_at limit 4`,
 db()<Array<{id:string;clocked_in_at:Date}>>`select id,clocked_in_at from timesheets where organization_id=${u.organizationId} and employee_id=${u.employeeId} and status='OPEN' order by clocked_in_at desc limit 1`,
 db()<Array<{count:number}>>`select count(*)::int count from requests where organization_id=${u.organizationId} and employee_id=${u.employeeId} and status='PENDING'`,
 db()<Array<{count:number}>>`select count(*)::int count from shift_transfers where organization_id=${u.organizationId} and target_employee_id=${u.employeeId} and status='PENDING_EMPLOYEE'`,
 db()<Array<{count:number}>>`select count(*)::int count from notifications where organization_id=${u.organizationId} and user_id=${u.userId} and read_at is null`
]);const tz=location[0]?.timezone||'Europe/Copenhagen';const next=shifts[0];return <div className="employee-page employee-home"><p className="eyebrow">Employee portal</p><h1>Hi, {u.name.split(' ')[0]}</h1><section className="employee-hero"><span><CalendarDays size={21}/></span><div><small>Next shift</small>{next?<><strong>{new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',timeZone:tz}).format(new Date(next.starts_at))}</strong><p>{fmt(next.starts_at,tz)}–{fmt(next.ends_at,tz)} · {next.role}</p></>:<><strong>No upcoming shifts</strong><p>Your published shifts will appear here.</p></>}</div></section><section className="employee-home-grid"><Link href="/employee/hours"><Clock3/><span><small>Time clock</small><strong>{active.length?'Clocked in':'Ready'}</strong></span><ChevronRight/></Link><Link href="/employee/shifts"><CalendarDays/><span><small>Upcoming</small><strong>{shifts.length} shifts</strong></span><ChevronRight/></Link><Link href="/employee/requests"><Umbrella/><span><small>Pending requests</small><strong>{requests[0]?.count||0}</strong></span><ChevronRight/></Link><Link href="/employee/notifications"><Bell/><span><small>Needs attention</small><strong>{(transfers[0]?.count||0)+(notifications[0]?.count||0)}</strong></span><ChevronRight/></Link></section><h2>Coming up</h2><section className="employee-list">{shifts.slice(0,3).map(s=><Link href="/employee/shifts" key={s.id}><div className="date-tile"><b>{new Intl.DateTimeFormat('en',{day:'2-digit',timeZone:tz}).format(new Date(s.starts_at))}</b><span>{new Intl.DateTimeFormat('en',{month:'short',timeZone:tz}).format(new Date(s.starts_at))}</span></div><div><strong>{s.role}</strong><p>{fmt(s.starts_at,tz)}–{fmt(s.ends_at,tz)} · {s.location_name}</p></div><ChevronRight size={18}/></Link>)}{!shifts.length&&<div className="empty-portal">No upcoming shifts</div>}</section></div>}
function fmt(d:Date,tz:string){return new Intl.DateTimeFormat('en-DK',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:tz}).format(new Date(d))}
