import { NextResponse } from "next/server";
import { requireCapability } from "@/lib/auth/session";
import { db } from "@/lib/db/client";
import { ApiError, enumValue, jsonError, readJsonObject, requiredString, uuid } from "@/lib/http";

export async function GET(req:Request){try{const user=await requireCapability("operations.read");const url=new URL(req.url);const locationId=uuid(url.searchParams.get("locationId")||user.locationId,"locationId");const serviceDate=url.searchParams.get("date")||new Date().toISOString().slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(serviceDate))throw new ApiError(400,"Invalid date");return NextResponse.json({date:serviceDate,items:await db()`select * from operation_checklist_items where organization_id=${user.organizationId} and location_id=${locationId} and service_date=${serviceDate}::date order by sort_order,created_at`});}catch(e){return jsonError(e)}}
export async function POST(req:Request){try{const user=await requireCapability("operations.manage");const body=await readJsonObject(req,16000);const locationId=uuid(body.locationId||user.locationId,"locationId");const title=requiredString(body,"title",160);const taskType=enumValue(body.taskType||"Task","taskType",["Opening","Closing","Task","Maintenance"] as const);const ownerLabel=typeof body.ownerLabel==="string"&&body.ownerLabel.trim()?body.ownerLabel.trim().slice(0,80):"Unassigned";const dueLabel=typeof body.dueLabel==="string"&&body.dueLabel.trim()?body.dueLabel.trim().slice(0,80):"Today";const [row]=await db()`insert into operation_checklist_items(organization_id,location_id,service_date,title,task_type,owner_label,due_label,created_by) select ${user.organizationId},id,current_date,${title},${taskType},${ownerLabel},${dueLabel},${user.userId} from locations where id=${locationId} and organization_id=${user.organizationId} and active returning *`;if(!row)throw new ApiError(404,"Active location not found");return NextResponse.json(row,{status:201});}catch(e){return jsonError(e)}}
export async function PATCH(req:Request){try{const user=await requireCapability("operations.manage");const body=await readJsonObject(req,8000);const id=uuid(body.id,"id");const done=body.done===undefined?null:Boolean(body.done);const ownerLabel=typeof body.ownerLabel==="string"?body.ownerLabel.trim().slice(0,80):null;const dueLabel=typeof body.dueLabel==="string"?body.dueLabel.trim().slice(0,80):null;const [row]=await db()`update operation_checklist_items set completed_at=case when ${done}::boolean is null then completed_at when ${done} then now() else null end,completed_by=case when ${done}::boolean is null then completed_by when ${done} then ${user.userId} else null end,owner_label=coalesce(${ownerLabel},owner_label),due_label=coalesce(${dueLabel},due_label),updated_at=now() where id=${id} and organization_id=${user.organizationId} and service_date=current_date returning *`;if(!row)throw new ApiError(404,"Checklist item not found");return NextResponse.json(row);}catch(e){return jsonError(e)}}
export async function DELETE(req:Request){try{const user=await requireCapability("operations.manage");const id=uuid(new URL(req.url).searchParams.get("id"),"id");const [row]=await db()`delete from operation_checklist_items where id=${id} and organization_id=${user.organizationId} and service_date=current_date returning id`;if(!row)throw new ApiError(404,"Checklist item not found");return NextResponse.json({ok:true});}catch(e){return jsonError(e)}}
