import { NextResponse } from "next/server";
import { requireUser } from "@/lib/auth/session";
import { db } from "@/lib/db/client";
import { ApiError, enumValue, jsonError, readJsonObject, requiredString, uuid } from "@/lib/http";
const roles=["OWNER","ADMIN","MANAGER","SHIFT_MANAGER"] as const;
export async function GET(req:Request){try{const user=await requireUser([...roles]);const locationId=uuid(new URL(req.url).searchParams.get("locationId")||user.locationId,"locationId");return NextResponse.json({items:await db()`select * from operation_checklist_items where organization_id=${user.organizationId} and location_id=${locationId} and service_date=current_date order by sort_order,created_at`});}catch(e){return jsonError(e)}}
export async function POST(req:Request){try{const user=await requireUser([...roles]);const body=await readJsonObject(req,16000);const locationId=uuid(body.locationId||user.locationId,"locationId");const title=requiredString(body,"title",160);const taskType=enumValue(body.taskType||"Task","taskType",["Opening","Closing","Task","Maintenance"] as const);const [row]=await db()`insert into operation_checklist_items(organization_id,location_id,service_date,title,task_type,owner_label,due_label,created_by) select ${user.organizationId},id,current_date,${title},${taskType},'Unassigned','Today',${user.userId} from locations where id=${locationId} and organization_id=${user.organizationId} and active returning *`;if(!row)throw new ApiError(404,"Active location not found");return NextResponse.json(row,{status:201});}catch(e){return jsonError(e)}}
export async function PATCH(req:Request){try{const user=await requireUser([...roles]);const body=await readJsonObject(req,8000);const id=uuid(body.id,"id");const done=Boolean(body.done);const [row]=await db()`update operation_checklist_items set completed_at=${done?new Date():null},completed_by=${done?user.userId:null},updated_at=now() where id=${id} and organization_id=${user.organizationId} and service_date=current_date returning *`;if(!row)throw new ApiError(404,"Checklist item not found");return NextResponse.json(row);}catch(e){return jsonError(e)}}
export async function DELETE(req:Request){try{const user=await requireUser([...roles]);const id=uuid(new URL(req.url).searchParams.get("id"),"id");const [row]=await db()`delete from operation_checklist_items where id=${id} and organization_id=${user.organizationId} and service_date=current_date returning id`;if(!row)throw new ApiError(404,"Checklist item not found");return NextResponse.json({ok:true});}catch(e){return jsonError(e)}}
