"use client";
import { PanelTitle, WorkspaceHeader } from "@/components/ui/workspace-ui";
import { CalendarDays, Check, Database, DownloadCloud, KeyRound, ReceiptText, RotateCcw, ShieldCheck, Upload } from "lucide-react";
export function ControlCenterWorkspace({devMode,databaseStatus,notify}:{devMode:boolean;databaseStatus:string;notify:(s:string)=>void}) {
 const groups=[
  {title:"Database & payroll",icon:Database,items:["All manager modules use tenant-scoped PostgreSQL APIs","Permanent payroll export ledger with SHA-256 hashes","Open, locked, exported and closed payroll periods","Payroll IDs, salary codes and cost centres"]},
  {title:"Attendance controls",icon:KeyRound,items:["Kiosk PIN verification and lockout","Venue geofence radius validation","Late, missed clock-out and geofence alerts","Employee timesheet correction requests"]},
  {title:"Scheduling",icon:CalendarDays,items:["Drag shifts between dates","Occurrence, future and whole-series editing","Reusable schedule templates","Availability, leave and overlap conflict checks","Labour revenue forecasts","Publish notifications and acknowledgements"]},
  {title:"Stock operations",icon:ReceiptText,items:["Delivery receiving and partial/disputed receipts","Invoice number, total and discrepancy matching","Waste logs with stock ledger entries","Draft, in-transit and received location transfers"]},
  {title:"Security & compliance",icon:ShieldCheck,items:["MFA factor foundation and recovery records","Password-reset tokens and rate limiting","Managed backup/restore runbook and health events","GDPR export, deletion and rectification requests"]}
 ];
 return <><WorkspaceHeader title="Control centre" description="Production controls plus development-data tools for realistic testing before database setup." actions={<span className={`connection-pill ${devMode?"dev":"live"}`}>{databaseStatus}</span>}/>{devMode&&<section className="card card-flush dev-data-tools"><PanelTitle title="Development data" description="Your workspace is saved in this browser. Export a backup or reset to the original demo data."/><div><button className="secondary" onClick={()=>{const raw=localStorage.getItem("barops-dev-v0101") || localStorage.getItem("barops-dev-v091") || localStorage.getItem("barops-dev-v070")||"{}";const blob=new Blob([raw],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="bar-ops-development-data.json";a.click();URL.revokeObjectURL(url);notify("Development data exported")}}><DownloadCloud size={17}/>Export JSON</button><label className="secondary file-import"><Upload size={17}/>Import JSON<input type="file" accept="application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{JSON.parse(await file.text());localStorage.setItem("barops-dev-v0101",await file.text());location.reload()}catch{notify("That file is not valid Bar Ops JSON")}}}/></label><button className="secondary danger-outline" onClick={()=>{if(confirm("Reset all development data to the original demo workspace?")){localStorage.removeItem("barops-dev-v0101"); localStorage.removeItem("barops-dev-v091"); localStorage.removeItem("barops-dev-v070");location.reload()}}}><RotateCcw size={17}/>Reset demo data</button></div></section>}<div className="control-grid">{groups.map(g=>{const Icon=g.icon;return <section className="card control-card" key={g.title}><div className="control-icon"><Icon size={20}/></div><h2>{g.title}</h2>{g.items.map(i=><p key={i}><Check size={15}/>{i}</p>)}</section>})}</div><section className="card card-flush control-actions"><PanelTitle title="Production status" description="Only workflows connected to a complete manager interface are presented as operational. Backend foundations remain documented in Implementation status."/><p className="settings-note">Use Time & attendance for payroll and clock review, Inventory for product and stock controls, and Settings for location time-clock configuration.</p></section></>;
}

