"use client";
import { Dialog, DialogActions } from "@/components/ui/interaction-ui";
import { WorkspaceHeader } from "@/components/ui/workspace-ui";
import { useState } from "react";
import { AlertTriangle, Check, ClipboardList, History, Pencil, Plus, Search } from "lucide-react";
import type { Product } from "@/lib/data";
import type { Persist, StockAdjustment } from "@/features/workspace/types";
import { inventoryStyles, surfaceStyles } from "@/lib/ui-classes";
function money(value: number) { return new Intl.NumberFormat("da-DK", { style: "currency", currency: "DKK", maximumFractionDigits: 0 }).format(value); }
export function InventoryWorkspace({ products, setProducts, onNewProduct, onEditProduct, onStockCount, adjustments, setAdjustments, notify, devMode, selectedLocationId, persist }: { products: Product[]; setProducts: React.Dispatch<React.SetStateAction<Product[]>>; onNewProduct: () => void; onEditProduct: (product:Product)=>void; onStockCount:()=>void; adjustments:StockAdjustment[]; setAdjustments:React.Dispatch<React.SetStateAction<StockAdjustment[]>>; notify: (s: string) => void; devMode:boolean; selectedLocationId:string; persist:Persist }) {
  const [query, setQuery] = useState(""); const [onlyLow, setOnlyLow] = useState(false); const [category,setCategory]=useState("All categories");
  const filtered = products.filter((p) => p.active !== false && p.name.toLowerCase().includes(query.toLowerCase()) && (category==="All categories"||p.category===category) && (!onlyLow || p.stock < p.par));
  const value = products.reduce((sum, product) => sum + product.stock * product.price, 0);
  const categories=["All categories",...Array.from(new Set(products.map(p=>p.category)))];
  async function adjust(product:Product,delta:number){ const reason=window.prompt(`Reason for ${delta>0?"adding":"removing"} ${Math.abs(delta)} ${product.unit}:`,delta>0?"Delivery / manual correction":"Waste / manual correction"); if(!reason)return; const nextStock=Math.max(0,product.stock+delta); try { if(!devMode) await persist("/api/products",{method:"PATCH",body:JSON.stringify({id:product.id,quantity:nextStock,locationId:selectedLocationId})}); setProducts(cur=>cur.map(p=>p.id===product.id?{...p,stock:nextStock}:p)); setAdjustments(cur=>[{id:crypto.randomUUID(),productId:product.id,productName:product.name,delta:nextStock-product.stock,reason,createdAt:new Date().toLocaleString("en-GB")},...cur].slice(0,30)); notify("Stock adjustment saved"); } catch(error) { notify(error instanceof Error?error.message:"Could not save stock adjustment"); } }
  return <div className={`${surfaceStyles.workspace} page-flow`}>
    <WorkspaceHeader title="Inventory" description="Stock, par levels and product controls." actions={<div className={`header-actions ${surfaceStyles.actions}`}><button className={`secondary ${surfaceStyles.control}`} onClick={onStockCount}><ClipboardList size={17} /> Stock count</button><button className={`primary ${surfaceStyles.control}`} onClick={onNewProduct}><Plus size={18} /> Add product</button></div>} />
    <section className={`${surfaceStyles.metrics} ${inventoryStyles.summary}`}><div className="card card-compact"><span>Stock value</span><strong>{money(value)}</strong></div><div className="card card-compact"><span>Products</span><strong>{products.filter(p=>p.active!==false).length}</strong></div><div className="card card-compact"><span>Below par</span><strong>{products.filter((p) => p.active!==false&&p.stock < p.par).length}</strong></div><div className="card card-compact"><span>Suppliers</span><strong>{new Set(products.map(p=>p.supplier)).size}</strong></div></section>
    <section className={inventoryStyles.productsPanel}><div className={`${surfaceStyles.toolbar} ${inventoryStyles.toolbar}`}><div className={surfaceStyles.search}><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search inventory" aria-label="Search inventory" /></div><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Filter inventory category">{categories.map(c=><option key={c}>{c}</option>)}</select><button className={`${surfaceStyles.control} ${inventoryStyles.lowFilter} ${onlyLow ? inventoryStyles.selected : ""}`} aria-pressed={onlyLow} onClick={() => setOnlyLow(!onlyLow)}><AlertTriangle size={16} /> Below par</button>{(query||category!=="All categories"||onlyLow)&&<button type="button" className={`${surfaceStyles.control} ${inventoryStyles.clear}`} onClick={()=>{setQuery("");setCategory("All categories");setOnlyLow(false)}}>Clear</button>}<span className={inventoryStyles.resultCount} role="status" aria-live="polite">{filtered.length} product{filtered.length===1?"":"s"}</span></div>
      <div className={inventoryStyles.productList}>{filtered.map((product) => { const suggested = Math.max(0, product.par - product.stock); return <article className={`${surfaceStyles.card} ${inventoryStyles.productCard}`} key={product.id}><header className={surfaceStyles.cardHeader}><div><p>{product.category}</p><h2>{product.name}</h2><small>{product.supplier} · {product.sku||"No SKU"}</small></div><button className={inventoryStyles.editButton} onClick={()=>onEditProduct(product)} aria-label={`Edit ${product.name}`}><Pencil size={15}/></button></header><div className={inventoryStyles.stockRow}><div><span>In stock</span><div className={inventoryStyles.stockControl}><button aria-label={`Remove one ${product.name}`} onClick={() => adjust(product,-1)}>−</button><strong className={product.stock < product.par ? inventoryStyles.low : ""}>{product.stock}</strong><button aria-label={`Add one ${product.name}`} onClick={() => adjust(product,1)}>+</button></div><small>{product.unit}</small></div><div><span>Par</span><strong>{product.par}</strong><small>Reorder at {product.reorderLevel??Math.max(0,product.par-2)}</small></div><div><span>Suggested</span>{suggested > 0 ? <strong className={inventoryStyles.suggestion}>+{suggested}</strong> : <strong className={inventoryStyles.ok}><Check size={14} /> OK</strong>}<small>{money(product.price)} / {product.unit}</small></div></div></article>})}{!filtered.length&&<div className={`${surfaceStyles.empty} ${inventoryStyles.empty}`}><strong>No products found</strong><span>Change the search or filters.</span></div>}</div>
    </section>
    <section className={`${surfaceStyles.card} ${inventoryStyles.history}`}><div className={surfaceStyles.cardHeader}><div><h2>Adjustment history</h2><p>Recent manual stock changes.</p></div><History size={18}/></div>{adjustments.length?<div>{adjustments.slice(0,8).map(a=><article key={a.id}><span className={a.delta>0?inventoryStyles.positive:inventoryStyles.negative}>{a.delta>0?"+":""}{a.delta}</span><span><b>{a.productName}</b><small>{a.reason}</small></span><time>{a.createdAt}</time></article>)}</div>:<p>No manual stock adjustments yet.</p>}</section>
  </div>
}

export function ProductDialog({ product, onClose, onSave }: { product?:Product; onClose: () => void; onSave: (product: Product) => void }) {
 const [name,setName]=useState(product?.name??""); const [supplier,setSupplier]=useState(product?.supplier??"Nordic Drinks"); const [category,setCategory]=useState(product?.category??"Draught beer"); const [stock,setStock]=useState(product?.stock??0); const [par,setPar]=useState(product?.par??6); const [reorderLevel,setReorderLevel]=useState(product?.reorderLevel??4); const [unit,setUnit]=useState(product?.unit??"units"); const [price,setPrice]=useState(product?.price??0); const [sellingPrice,setSellingPrice]=useState(product?.sellingPrice??0); const [sku,setSku]=useState(product?.sku??""); const [packSize,setPackSize]=useState(product?.packSize??1); const [notes,setNotes]=useState(product?.notes??""); const [active,setActive]=useState(product?.active!==false);
 function save(){if(!name.trim()){alert("Add a product name");return;}onSave({id:product?.id??crypto.randomUUID(),name:name.trim(),supplier,category,stock:Math.max(0,stock),par:Math.max(0,par),reorderLevel:Math.max(0,reorderLevel),unit,price:Math.max(0,price),sellingPrice:Math.max(0,sellingPrice),sku:sku.trim(),packSize:Math.max(1,packSize),notes:notes.trim(),active});}
 return <Dialog title={product?"Edit product":"Add product"} description="Maintain purchasing, pricing and location stock settings." onClose={onClose}><div className="form-grid"><label className="full-field">Product name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Lager 30L"/></label><label>Supplier<select value={supplier} onChange={e=>setSupplier(e.target.value)}><option>Nordic Drinks</option><option>Vin & Co.</option><option>Bar Supply DK</option><option>City Produce</option></select></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>Draught beer</option><option>Wine</option><option>Spirits</option><option>Soft drinks</option><option>Fresh</option><option>Consumables</option></select></label><label>Supplier SKU<input value={sku} onChange={e=>setSku(e.target.value)} placeholder="Optional"/></label><label>Unit<select value={unit} onChange={e=>setUnit(e.target.value)}><option>units</option><option>kegs</option><option>bottles</option><option>cases</option><option>pieces</option><option>kg</option><option>litres</option></select></label><label>Pack size<input type="number" min="1" value={packSize} onChange={e=>setPackSize(Number(e.target.value))}/></label><label>Current stock<input type="number" min="0" value={stock} onChange={e=>setStock(Number(e.target.value))}/></label><label>Par level<input type="number" min="0" value={par} onChange={e=>setPar(Number(e.target.value))}/></label><label>Reorder level<input type="number" min="0" value={reorderLevel} onChange={e=>setReorderLevel(Number(e.target.value))}/></label><label>Purchase price (DKK)<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(Number(e.target.value))}/></label><label>Selling price (DKK)<input type="number" min="0" step="0.01" value={sellingPrice} onChange={e=>setSellingPrice(Number(e.target.value))}/></label><label>Status<select value={active?"active":"inactive"} onChange={e=>setActive(e.target.value==="active")}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label className="full-field">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Storage, ordering or handling notes"/></label></div><DialogActions onClose={onClose} onConfirm={save} confirmLabel={product?"Save product":"Add product"}/></Dialog>
}

export function StockCountDialog({products,onClose,onSave}:{products:Product[];onClose:()=>void;onSave:(counts:Record<string,number>)=>void}){
 const [counts,setCounts]=useState<Record<string,number>>(()=>Object.fromEntries(products.filter(p=>p.active!==false).map(p=>[p.id,p.stock]))); const [showExpected,setShowExpected]=useState(false); const variances=products.filter(p=>p.active!==false).map(p=>({p,variance:(counts[p.id]??0)-p.stock}));
 return <Dialog title="Stock count" description="Enter actual quantities, review variance, then approve the count." onClose={onClose}><div className="count-toolbar"><label><input type="checkbox" checked={showExpected} onChange={e=>setShowExpected(e.target.checked)}/> Show expected stock</label><strong>{variances.filter(x=>x.variance!==0).length} variances</strong></div><div className="stock-count-list">{variances.map(({p,variance})=><label key={p.id}><span><b>{p.name}</b><small>{p.category} · {p.unit}{showExpected?` · expected ${p.stock}`:""}</small></span><input type="number" min="0" value={counts[p.id]??0} onChange={e=>setCounts(cur=>({...cur,[p.id]:Number(e.target.value)}))}/><i className={variance===0?"count-ok":variance>0?"count-over":"count-short"}>{variance===0?"Match":`${variance>0?"+":""}${variance}`}</i></label>)}</div><DialogActions onClose={onClose} onConfirm={()=>onSave(counts)} confirmLabel="Approve stock count"/></Dialog>
}
