"use client";
import { PanelTitle, WorkspaceHeader } from "@/components/ui/workspace-ui";
import { useEffect, useState } from "react";
import { Check, ClipboardList, NotebookPen, Pencil, Plus, Send, Trash2, Wrench } from "lucide-react";
import type { LogEntry, OpsTask } from "@/features/workspace/types";
import { parseOperationChecklistRecords } from "@/features/operations/types";
import { operationsStyles, surfaceStyles } from "@/lib/ui-classes";
export function DailyOperationsWorkspace({tasks,setTasks,logs,setLogs,notify,devMode,locationId}:{tasks:OpsTask[];setTasks:React.Dispatch<React.SetStateAction<OpsTask[]>>;logs:LogEntry[];setLogs:React.Dispatch<React.SetStateAction<LogEntry[]>>;notify:(s:string)=>void;devMode:boolean;locationId:string}){
 const [title,setTitle]=useState(""); const [type,setType]=useState<OpsTask["type"]>("Task"); const [logText,setLogText]=useState(""); const [savingId,setSavingId]=useState<string|null>(null);const [serviceDate,setServiceDate]=useState(()=>new Date().toISOString().slice(0,10));
 const complete=tasks.filter(t=>t.done).length; const isToday=serviceDate===new Date().toISOString().slice(0,10);
 useEffect(()=>{if(devMode||!locationId)return;fetch(`/api/operation-checklists?locationId=${encodeURIComponent(locationId)}&date=${encodeURIComponent(serviceDate)}`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load checklist");return d}).then(d=>setTasks(parseOperationChecklistRecords(d).map((x)=>({id:x.id,title:x.title,type:x.task_type,owner:x.owner_label||"Unassigned",due:x.due_label||"Today",done:Boolean(x.completed_at)})))).catch(e=>notify(e.message));},[devMode,locationId,serviceDate]);
 async function addTask(){if(!title.trim())return; if(devMode){setTasks(cur=>[...cur,{id:crypto.randomUUID(),title:title.trim(),type,owner:"Unassigned",due:"Today",done:false}]);setTitle("");notify("Operational task added");return;} try{const r=await fetch("/api/operation-checklists",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locationId,title:title.trim(),taskType:type})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not add task");setTasks(cur=>[...cur,{id:d.id,title:d.title,type:d.task_type,owner:d.owner_label||"Unassigned",due:d.due_label||"Today",done:false}]);setTitle("");notify("Operational task added");}catch(e){notify(e instanceof Error?e.message:"Could not add task");}}
 async function addPreset(preset:"Opening"|"Closing"){const titles=preset==="Opening"?["Check tills and floats","Check fridges and ice","Prepare garnishes and bar stations","Confirm toilets and guest areas are ready"]:["Complete final stock check","Clean bar stations and equipment","Lock doors and secure cash","Set alarm and record handover notes"];for(const itemTitle of titles){if(devMode){setTasks(cur=>[...cur,{id:crypto.randomUUID(),title:itemTitle,type:preset,owner:"Shift manager",due:preset==="Opening"?"Before opening":"Before close",done:false}]);continue;}const r=await fetch("/api/operation-checklists",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locationId,title:itemTitle,taskType:preset})});const d=await r.json();if(!r.ok){notify(d.error||`Could not add ${preset.toLowerCase()} checklist`);return;}setTasks(cur=>[...cur,{id:d.id,title:d.title,type:d.task_type,owner:d.owner_label||"Unassigned",due:d.due_label||"Today",done:false}]);}notify(`${preset} checklist added`);}
 async function toggleTask(task:OpsTask){if(devMode){setTasks(cur=>cur.map(x=>x.id===task.id?{...x,done:!x.done}:x));return;}setSavingId(task.id);try{const r=await fetch("/api/operation-checklists",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:task.id,done:!task.done})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not update task");setTasks(cur=>cur.map(x=>x.id===task.id?{...x,done:Boolean(d.completed_at)}:x));}catch(e){notify(e instanceof Error?e.message:"Could not update task");}finally{setSavingId(null);}}
 async function removeTask(task:OpsTask){if(devMode){setTasks(cur=>cur.filter(x=>x.id!==task.id));return;}try{const r=await fetch(`/api/operation-checklists?id=${encodeURIComponent(task.id)}`,{method:"DELETE"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Could not remove task");setTasks(cur=>cur.filter(x=>x.id!==task.id));}catch(e){notify(e instanceof Error?e.message:"Could not remove task");}}
 async function editTaskMeta(task:OpsTask){const owner=window.prompt("Who owns this task?",task.owner);if(owner===null)return;const due=window.prompt("When is it due?",task.due);if(due===null)return;if(devMode){setTasks(cur=>cur.map(x=>x.id===task.id?{...x,owner:owner.trim()||"Unassigned",due:due.trim()||"Today"}:x));return;}try{const r=await fetch("/api/operation-checklists",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:task.id,ownerLabel:owner.trim()||"Unassigned",dueLabel:due.trim()||"Today"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not update task");setTasks(cur=>cur.map(x=>x.id===task.id?{...x,owner:d.owner_label||"Unassigned",due:d.due_label||"Today"}:x));notify("Task responsibility updated");}catch(e){notify(e instanceof Error?e.message:"Could not update task");}}
 function addLog(){if(!logText.trim())return;setLogs(cur=>[{id:crypto.randomUUID(),title:"Shift handover",body:logText.trim(),author:"Current manager",createdAt:new Date().toLocaleString("en-GB")},...cur]);setLogText("");notify("Handover note saved");}
 return <div className={`${operationsStyles.workspace} page-flow`}>
 <div className={operationsStyles.header}><WorkspaceHeader title="Daily operations" description="Opening, closing, handovers and maintenance in one live manager workspace." actions={<div className={operationsStyles.headerActions}><input className={operationsStyles.dateInput} type="date" value={serviceDate} max={new Date().toISOString().slice(0,10)} onChange={e=>setServiceDate(e.target.value)} aria-label="Checklist date"/><span className={`connection-pill dev ${operationsStyles.progress}`}>{complete}/{tasks.length} complete</span></div>}/></div>
 <section className={`${surfaceStyles.metrics} ${operationsStyles.summary}`} aria-label="Daily operations summary"><article className="card card-compact"><ClipboardList/><span>Opening & closing<strong>{tasks.filter(t=>t.type==="Opening"||t.type==="Closing").length} checks</strong></span></article><article className="card card-compact"><Wrench/><span>Maintenance<strong>{tasks.filter(t=>t.type==="Maintenance"&&!t.done).length} open</strong></span></article><article className="card card-compact"><NotebookPen/><span>Logbook<strong>{logs.length} entries</strong></span></article></section>
 <div className={operationsStyles.layout}><section className={`${operationsStyles.panel} ${operationsStyles.checklist}`}><PanelTitle title="Today’s checklist" description="Completion is shared with every manager at this location."/>{isToday&&<div className={operationsStyles.presets}><button type="button" className="secondary" onClick={()=>addPreset("Opening")}><Plus size={15}/>Opening checklist</button><button type="button" className="secondary" onClick={()=>addPreset("Closing")}><Plus size={15}/>Closing checklist</button></div>}<div className={operationsStyles.taskList}>{tasks.map(t=><article key={t.id} className={`${operationsStyles.task} ${t.done?"task-done":""}`}><button type="button" className="task-check" disabled={!isToday||savingId===t.id} onClick={()=>toggleTask(t)}>{t.done?<Check size={16}/>:null}</button><span><b>{t.title}</b><small>{t.type} · {t.owner} · {t.due}</small></span>{isToday&&<span className={operationsStyles.rowActions}><button type="button" className="icon-button" onClick={()=>editTaskMeta(t)} aria-label={`Edit responsibility for ${t.title}`}><Pencil size={15}/></button><button type="button" className="icon-button" onClick={()=>removeTask(t)} aria-label={`Remove ${t.title}`}><Trash2 size={15}/></button></span>}</article>)}</div>{isToday&&<div className={operationsStyles.create}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Add an operational task"/><select value={type} onChange={e=>setType(e.target.value as OpsTask["type"])}><option>Task</option><option>Opening</option><option>Closing</option><option>Maintenance</option></select><button type="button" className="primary" onClick={addTask}><Plus size={16}/>Add</button></div>}</section>
 <section className={`${operationsStyles.panel} ${operationsStyles.logbook}`}><PanelTitle title="Manager logbook" description="Permanent shift handovers and important operational context."/><div className={operationsStyles.compose}><textarea value={logText} onChange={e=>setLogText(e.target.value)} placeholder="What does the next manager need to know?"/><button type="button" className="primary" onClick={addLog}><Send size={16}/>Save handover</button></div><div className={operationsStyles.logList}>{logs.map(l=><article className={operationsStyles.logEntry} key={l.id}><div><b>{l.title}</b><small>{l.author} · {l.createdAt}</small></div><p>{l.body}</p></article>)}</div></section></div></div>
}

